name: Release Deployer Service

on:
  push:
    tags:
      - 'v*'         # e.g., v1.0.0

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # needed for creating GitHub releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      # NOTE: CGO_ENABLED=0 produces a statically compiled binary that avoids
      # runtime errors I was getting on Amazon Linux 2
      - name: Build for Amazon Linux 2 (linux/amd64)
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -o deployer-service \
          -buildvcs=false \
          -ldflags "-X main.version=$(git describe --tags --abbrev=0)"


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: deployer-service
